// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbjxRjvaQpLcp-4YES17D759hshgKMb70',
    appId: '1:329712688612:web:45a025d2a7be45acd4fbf1',
    messagingSenderId: '329712688612',
    projectId: 'care-sync-bbc17',
    authDomain: 'care-sync-bbc17.firebaseapp.com',
    storageBucket: 'care-sync-bbc17.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqugt-nSiHZV1yezSBcAcEI1T5xOsKtCI',
    appId: '1:329712688612:android:7ad329506df5a57bd4fbf1',
    messagingSenderId: '329712688612',
    projectId: 'care-sync-bbc17',
    storageBucket: 'care-sync-bbc17.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7RwqE00ck1qpGCNBAciufOpnzDyfjE-Q',
    appId: '1:329712688612:ios:77acf80c9e632f33d4fbf1',
    messagingSenderId: '329712688612',
    projectId: 'care-sync-bbc17',
    storageBucket: 'care-sync-bbc17.firebasestorage.app',
    iosBundleId: 'com.example.careSync',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7RwqE00ck1qpGCNBAciufOpnzDyfjE-Q',
    appId: '1:329712688612:ios:77acf80c9e632f33d4fbf1',
    messagingSenderId: '329712688612',
    projectId: 'care-sync-bbc17',
    storageBucket: 'care-sync-bbc17.firebasestorage.app',
    iosBundleId: 'com.example.careSync',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDbjxRjvaQpLcp-4YES17D759hshgKMb70',
    appId: '1:329712688612:web:5f983c9b8c107fabd4fbf1',
    messagingSenderId: '329712688612',
    projectId: 'care-sync-bbc17',
    authDomain: 'care-sync-bbc17.firebaseapp.com',
    storageBucket: 'care-sync-bbc17.firebasestorage.app',
  );
}
